### ISSUE TITLE
Death Match Never Starts

### ISSUE THREAD

**Issue by BobbyTowers** [InfinityGamers/HungerGames#1]
All my players join fine and it shows HG has started. It shows that the deathmatch will start in three mins but it never gave a notice it started. 

Can you turn off damage before the deathmatch starts?

**Comment by xBeastMode** [comment]
Death match is for players to fight if they can't find eachother, but this will be added later. I will see about the notice issue. :)

**Comment by xBeastMode** [comment]
Issue fixed. Download latest release :smile:
