### ISSUE TITLE
Build 9

### ISSUE THREAD

**Issue by XiangZhao969** [InfinityGamers/HungerGames#11]
- players can move while the countdown is still on
- map still hasn't reset ( i tried flint and steel and in the next match it still burning)
- player wins the match although burned to death (broadcast)

**Comment by xBeastMode** [comment]
1. This is not a PocketMine bug, only happens with third part builds of PocketMine like genisys, ImagicalMine, clearsky, etc. So I cannot fix that one.
2. I will try and fix this, it seems to be a problem, thanks for reporting.
3. Can you explain better? Thanks.

**Comment by XiangZhao969** [comment]
I mean i suicided but the plugin said i'm the winner

**Comment by xBeastMode** [comment]
Like when you do /kill?

**Comment by kaitododoyt** [comment]
Xbeast Man, u said the same to me, can you let me the official build link please, thanks

**Comment by xBeastMode** [comment]
http://cdn.pocketmine.net/api/update-development.phar

**Comment by XiangZhao969** [comment]
Tested on pocketmine
- when /hg quit, the game ends and broadcast the quiter a winner
- no inv reset
- no map rs/protect
- deathmatch sometimes happen soonly
- broadcast isn't correct, loser is broadcasted to be a winner

**Comment by xBeastMode** [comment]
Plugin is inactive. I will return in 3 days.

**Comment by xBeastMode** [comment]
THIS PLUGIN IS BEING RE WRITTEN.
