### ISSUE TITLE
Illegal Offset

### ISSUE THREAD

**Issue by BobbyTowers** [InfinityGamers/HungerGames#2]
Warning: Illegal offset type in isset or empty in phar://C:/Users/Bobby-Foo/Documents/MCPE SQL/plugins/HungerGames.phar/src/xbeastmode/hg/tasks/MessageTask.php on line 20

**Comment by xBeastMode** [comment]
Will take a look at that.

**Comment by xBeastMode** [comment]
Issue fixed. Download latest release :smile:
