### ISSUE TITLE
if you are played with 2 players the player leave and the leaved player win the game

### ISSUE THREAD

**Issue by dries-c** [InfinityGamers/HungerGames#20]

**Comment by dries-c** [comment]
only the

**Comment by xBeastMode** [comment]
I know the issue but wait till I fix it.

**Comment by ghost** [comment]
@xBeastMode  can you hurry up dude ? Its been a month

**Comment by xBeastMode** [comment]
No... :(
I abandoned this plugin project, and I don't have the desire to create or update plugins, sorry. There's another HG plugin called SurvivalGamesV3, you can go ahead and try it, or ask some dev if they would wanna update this plugin. Sorry...

**Comment by xZeroMCPE** [comment]
or try github.com/andrethegamer/SurvivalGame

**Comment by dries-c** [comment]
Thats not working many many bugs

**Comment by xBeastMode** [comment]
This plugin will be updated soon.
