### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dries-c** [InfinityGamers/HungerGames#22]
Notice: Undefined index: Map1 in /Users/Ronny/Desktop/V9/plugins/HungerGames-master/src/xbeastmode/hg/tasks/GameTask.php on line 33

Warning: Invalid argument supplied for foreach() in /Users/Ronny/Desktop/V9/plugins/HungerGames-master/src/xbeastmode/hg/tasks/GameTask.php on line 33

**Comment by xBeastMode** [comment]
Need to set it up right

**Comment by dries-c** [comment]
It work  i have only this error in console

**Comment by xBeastMode** [comment]
This plugin will be updated soon.
