### ISSUE TITLE
Auto Chest Filling

### ISSUE THREAD

**Issue by mikerudie** [InfinityGamers/HungerGames#27]
Not sure what I'm doing wrong, but this feature does not appear to be working for me.  I have chests placed in the world, but they do not get filled with anything prior to a game starting.

**Comment by xBeastMode** [comment]
Sorry, I am not longer active on this. Here's another Hunger Games plugin: https://github.com/imagicalgamer

**Comment by xBeastMode** [comment]
I am no longer updating my plugins. Please use this plugin:

https://github.com/imagicalgamer/survivalgamesv3
