### ISSUE TITLE
Bug, i dont know how to fix, is much code

### ISSUE THREAD

**Issue by Fake20154** [InfinityGamers/HungerGames#28]
When you are two players you kill the enemy and not win the game

**Comment by dries-c** [comment]
Use the verion from the IM forums

**Comment by Fake20154** [comment]
can you give me the link please

**Comment by Fake20154** [comment]
oh i know now, thanks..

**Comment by Fake20154** [comment]
i cant not download plugins in IM

**Comment by Fake20154** [comment]
Can you just give me the download from mediafire pleeease

**Comment by Fake20154** [comment]
the imagicalmine website (forum) is offline

**Comment by dries-c** [comment]
Forums.imagicalmine.net
