### ISSUE TITLE
World

### ISSUE THREAD

**Issue by kaitododoyt** [InfinityGamers/HungerGames#3]
This support multiworld?, i have the problem:

ArrayOutOfBoundsException: "Undefined index: level" (                                                                                E_NOTICE) in "/ph
ar_HungerGames-master_3yoJO8QP5m3m1vN.phar/src/xbeastmode/hg/etc/EndGam                                                                                e" at line 46

The game doesn´t end

**Comment by xBeastMode** [comment]
Issue fixed. Please download latest release :smile:
