### ISSUE TITLE
no countdown 

### ISSUE THREAD

**Issue by dries-c** [InfinityGamers/HungerGames#30]
Elywing thread:CRITICAL > ClassNotFoundException: "Class hungergames\lib\utils\Loader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by xBeastMode** [comment]
If you compile it using pmt.mcpe.me it will become corrupted. Please use this release instead: https://github.com/InfinityGamers/HungerGames-UPDATED/releases/tag/Build%2316

**Comment by dries-c** [comment]
K thx

Op 29-dec.-2016 23:12 schreef "xBeastMode" <notifications@github.com>:
