### ISSUE TITLE
how to even join a game?...

### ISSUE THREAD

**Issue by austina1212** [InfinityGamers/HungerGames#33]
As the title says

**Comment by xZeroMCPE** [comment]
Closing this issue, The title is not for the description....

![test](https://i.gyazo.com/ffc46c664777f158d820b805e5a255b2.png)

**Comment by austina1212** [comment]
-_- nice try with your fake "This issue was closed"...

**Comment by austina1212** [comment]
So, anyone know how to make signs?

**Comment by xZeroMCPE** [comment]
Although, make another issue with proper format.... and close this

Will make you look more *** instead of looking like a lost hobo!

**Comment by xBeastMode** [comment]
How do you want to join a game? Please explain in a new issue.
