### ISSUE TITLE
Freeze after x minutes

### ISSUE THREAD

**Issue by dries-c** [InfinityGamers/HungerGames#35]
Version: Build#16
Software: Elywing
Idk what reason

config: http://pastebin.com/7mEqPmXR

**Comment by xBeastMode** [comment]
When does it freeze? During the waiting to start or when the game is running?

**Comment by dries-c** [comment]
both

**Comment by xBeastMode** [comment]
Maybe this is a Elywing issue.

**Comment by dries-c** [comment]
idk its also with pmmp

**Comment by xBeastMode** [comment]
Do you have enough RAM?

**Comment by xBeastMode** [comment]
I think I found the issue. I will try to fix it.
