### ISSUE TITLE
Gamemode / items not reset?

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#36]
I've been testing this on my server and noticed a couple of issues with this otherwise awesome plugin.

1. When a user joins a HungerGames their gamemode is not automatically set to survival (therefore creative players can never be killed).
2. Items the player has in inventory when joining a HungerGames are brought with them to the game (therefore allowing full diamond / gapple etc from the start of the game).
3. Items gained during the HungerGames are not lost when the game ends (therefore allowing people to get  items they can use in other worlds). There original inventory  should be restored based upon point 2.

Hope these points will help you to fix an otherwise perfect plugin. Thank you for your time and effort in developing this :-)

**Comment by xBeastMode** [comment]
Yes, I will soon add a fix this. Maybe with a script it'll be enough. :D

**Comment by Arantxia** [comment]
Is this already fixed?

**Comment by xBeastMode** [comment]
No.

**Comment by xBeastMode** [comment]
Plugin discontinued.
