### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#37]
Yes, I compiled it with DevTools. It happened when I tap the sign.

**Comment by ghost** [comment]
[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'HungerGames vBuild#16': Class hungergames\lib\utils\Loader not found on hungergames\EventListener
[20:34:10] [Server thread/CRITICAL]: ClassNotFoundException: "Class hungergames\lib\utils\Loader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by xBeastMode** [comment]
Don't compile on your own. Download here:
https://github.com/InfinityGamers/HungerGames-UPDATED/releases/download/Build%2316/HungerGames_vBuild.16.phar

**Comment by ghost** [comment]
I am testing it.
