### ISSUE TITLE
Incompatible API

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#38]
I downloaded this version https://github.com/InfinityGamers/HungerGames-UPDATED/releases/download/Build%2316/HungerGames_vBuild.16.phar but it has got incompatible API. I am using latest version of Genisys software with API 3.0.0-ALPHA3.

**Comment by xBeastMode** [comment]
Try this: https://github.com/InfinityGamers/HungerGames-UPDATED/releases/download/Build%2316-API3/HungerGames_Build.16.New.API.phar
