### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by xBeastMode** [InfinityGamers/HungerGames#41]
Here's the TODO list for Build#17:
+ Add Kits
+ Add GUI Kit selector
+ Add AdvancedKits support
+ Add tap-to-add-slot support
+ Add API events
+ Add Command to join game automatically
+ Add Statistics API
+ Add spectator mode
+ Optimize plugin for better performance

**Comment by ghost** [comment]
It is great now and after this it will be really AAAAAWWWWEEESOME :-)!

**Comment by InspectorGadget** [comment]
GUI should be easier to use after 1.0.4 update...

**Comment by xBeastMode** [comment]
Additions to the TODO list:
+ Allow kicking player from game
+ Allow banning player from game
+ Allow VIP players to join full match
+ Allow to put game in maintainance mode

**Comment by InspectorGadget** [comment]
Cool! 👍

**Comment by TheDiamondYT1** [comment]
I recommend using checkboxes for a TODO list 

- [ ] Thing

> Above done using: - [ ] Thing

**Comment by xBeastMode** [comment]
I'll probably do it all together.

**Comment by xBeastMode** [comment]
Plugin discontinued.

**Comment by TheDiamondYT1** [comment]
@xBeastMode I think that was a typo. Let me fix it for you:
> Plugin discontinued by me, continued by BlockHorizons.
