### ISSUE TITLE
Signs Not Refreshing

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#42]
My signs aren't updating they just say hg SG1?

**Comment by xBeastMode** [comment]
Can you take a screenshot and upload it somewhere?

**Comment by ghost** [comment]
Sure

**Comment by ghost** [comment]
Join my server

**Comment by ghost** [comment]
See for your self. Do you want to do that?

**Comment by xBeastMode** [comment]
I don't know your server...

**Comment by ghost** [comment]
I will give it to you the ip is 159.203..11.26 and the port is default. I will be on so I will see you there. By the way it must be on 1.0.4

**Comment by ghost** [comment]
Sorry, messed up on the ip. It is 159.203.11.26

**Comment by ghost** [comment]
Who cares, this is a screenshot https://ibb.co/eyUniv

**Comment by xBeastMode** [comment]
I joined but I'm stuck inside water.

**Comment by ghost** [comment]
Please re-join and I will be there

**Comment by xBeastMode** [comment]
Sure
.

**Comment by xBeastMode** [comment]
Ok. You have to reload your server and it will be refreshed.

**Comment by ghost** [comment]
But I did /reload and I did stop and restart my server!

**Comment by xBeastMode** [comment]
Insert your arena config.

**Comment by xBeastMode** [comment]
Please start a new issue and follow the format: https://github.com/InfinityGamers/HungerGames-UPDATED/wiki/Creating-issues
