### ISSUE TITLE
Hungergames doesnt load correctly

### ISSUE THREAD

**Issue by xXSirGamesXx** [InfinityGamers/HungerGames#43]
So I created a hunger games map everything worked fine up until I tried joining
When I try joining it tp's me to one of the slots but, all it does is keep me in the spawn. There is no messages or anything it just keeps you in the slot. also /hg leave crashed server.  Only way to leave is by leaving the server. Thanks for helping in advance

**Comment by xBeastMode** [comment]
Please follow the issue format: https://github.com/InfinityGamers/HungerGames-UPDATED/wiki/Creating-issues
