### ISSUE TITLE
Feature Request: Add /HG join command

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#46]
Hello,
Could you please add a /hg join command, that would make it so I could click a slapper to join the game. This would be greatly appreciated. If you decide to add this please make it join a random game or make it so you can do /hg join <game-name>

/slapper edit <id> addcommand rca {player} hg join

**Comment by xBeastMode** [comment]
This and a auto join command will be added.

**Comment by ghost** [comment]
Timeline?

**Comment by xBeastMode** [comment]
Pardon??

**Comment by ghost** [comment]
What I mean is when do you think this we be complete?

**Comment by xBeastMode** [comment]
No idea, I can be wrong. Best guess is in the weekend.

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
How is it coming?

**Comment by xBeastMode** [comment]
@NFGamerMC it's going good, I am continuing my work on it.

**Comment by ghost** [comment]
Great

**Comment by xBeastMode** [comment]
Plugin discontinued.
