### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kaitododoyt** [InfinityGamers/HungerGames#5]
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\plugin\PluginDescription::loadMap() must be of the type array, boolean given, called in phar://C:/Users/Kaito/Desktop/kaito php7/PocketMine-MP.phar/src/pocketmine/plugin/PluginDescription.php on line 51" (EXCEPTION) in "/src/pocketmine/plugin/PluginDescription" at line 59

now, the server crash and cant load plugin :(

**Comment by xBeastMode** [comment]
Try to make a new game.

**Comment by xBeastMode** [comment]
Do you want me to set it up for you?

**Comment by kaitododoyt** [comment]
i downloaded latest versión and this is works good
