### ISSUE TITLE
Outdated API

### ISSUE THREAD

**Issue by MrBurglar214** [InfinityGamers/HungerGames#61]
Its is one API 3.0.0 ALPHA 3 please updated to 3.0.0 APLHA 7

**Comment by Arctiblaine** [comment]
-It was ALPHA8, now ALPHA9

**Comment by mrpwes** [comment]
Update For 3.0.0-ALPHA10 Thanks Guys

**Comment by Arctiblaine** [comment]
Guys, sorry but I think this plugin is dead... one of is gonna have to take one for the team...

**Comment by mrpwes** [comment]
Sad tiNsLeY799

**Comment by xBeastMode** [comment]
Yes, I've returned to update it once again, and it will be released on poggit soon.
