### ISSUE TITLE
Someone ? Can update this plugin ???? -> 3.0.0-Alpha10

### ISSUE THREAD

**Issue by mrpwes** [InfinityGamers/HungerGames#62]
If you have updated can you just put link ??????

SOME PLEASE UPDATE Or Develop This Plugin

**Comment by xBeastMode** [comment]
Yes, I've returned to update it once again, and it will be released on poggit soon.

**Comment by xBeastMode** [comment]
Let's discuss everything here: https://github.com/InfinityGamers/HungerGames-UPDATED/issues/61
