### ISSUE TITLE
reset map does not work

### ISSUE THREAD

**Issue by ImAMadDev** [InfinityGamers/HungerGames#69]

**Comment by xBeastMode** [comment]
Please be more descriptive, what plugin version are you using, what are you arena settings?

**Comment by ImAMadDev** [comment]
version:  HungerGames_dev-22.phar
arena settings : ---
sign_line_1: '&6-=&e[&fS&cW&e]&6=-'
sign_line_2: '&f{on}&f/&a{max}'
sign_line_3: '&aGame: &f{game}'
sign_line_4: '&eStatus: {status}'
is_sky_wars: "yes"
clear_inventory_on_join: true
min_players: 2
max_players: 12
game_seconds: 300.000000
waiting_seconds: 20.000000
game_level: Luxury
refill_chest_after_seconds: 150.000000
chest_items:
- 272 0 1
- 298 0 1
- 299 0 1
- 300 0 1
- 1 0 64
- 301 0 1
lobby_pos:
  level: Lobby
  x: 125.300000
  "y": 11.001000
  z: 130.000000
death_match_pos:
  level: Luxury
  x: 704.891500
  "y": 88.000000
  z: 2232.790000
slots:
  1:
    x: 687.456700
    "y": 89.000000
    z: 2280.271500
  2:
    x: 677.395800
    "y": 89.000000
    z: 2259.302700
  3:
    x: 656.601400
    "y": 89.000000
    z: 2249.544700
  4:
    x: 656.438000
    "y": 89.000000
    z: 2221.163800
  5:
  x: 677.558700
    "y": 89.000000
    z: 2211.328100
  6:
    x: 687.717300
    "y": 89.000000
    z: 2190.698000
  7:
    x: 715.359800
    "y": 89.000000
    z: 2190.215600
  8:
    x: 725.691400
    "y": 89.000000
    z: 2211.494600
  9:
    x: 746.330600
    "y": 89.000000
    z: 2221.724400
  10:
    x: 746.403300
    "y": 89.000000
    z: 2249.485400
  11:
    x: 725.459000
    "y": 89.000000
    z: 2259.347200
  12:
    x: 715.421300
    "y": 89.000000
    z: 2280.946300
sign_list:
  145:13:129:Lobby: ""
...

**Comment by xBeastMode** [comment]
Does it say resetting map in the console after a game ends?

**Comment by ImAMadDev** [comment]
yes

**Comment by xBeastMode** [comment]
Then why do you say it doesn't reset?

**Comment by ImAMadDev** [comment]
When I enter the arena, the blocks I place do not disappear and those I break do not re-establish themselves.

**Comment by xBeastMode** [comment]
Can I see for myself?

**Comment by ImAMadDev** [comment]
sure 
ip: skylordspvp.forcecraft.us
port: 25571

**Comment by Alderander** [comment]
Same. On my server reset the map also does not work (pmmp 1.7dev-600, hg build-18.2). Relog, reset, restart, nothing helps.

**Comment by xBeastMode** [comment]
When does this occur, during death match, during the game is going or anytime?

**Comment by Alderander** [comment]
I did not check with "death match". Just after join, finish and leaving to lobby the game does not reset the map, despite the message in the console "[HungerGames] Resetting map for game 'HG'". In options I also have _is_sky_wars: "yes"_ if this is important.

**Comment by xBeastMode** [comment]
I might know the issue. Remember ```is_sky_wars``` is only if you want it to be in skywars mode.

**Comment by Alderander** [comment]
ok, but changing this option does not resolve map reset after all players leave the match

**Comment by CarlosCraft1145** [comment]
When I try to set a map for a certain level (world), it gives me an error message. please help.

Thanks.

**Comment by CarlosCraft1145** [comment]
When I set it to skywars, the map does not reset. The blocks stay there.

**Comment by Vladucul** [comment]
It also doesn't reset for me. When I play a round of skywars, place blocks, and then leave the round, and play the same game after, the blocks I've placed before don't reset

**Comment by xBeastMode** [comment]
Check the new commit.
