### ISSUE TITLE
/hg join <game>

### ISSUE THREAD

**Issue by ghost** [InfinityGamers/HungerGames#70]
Every time I try to join a game all it does is bug out and all my players have to relog to stop it and even worse the /leave command doesn't work at all.

😿😿😿😿

**Comment by xBeastMode** [comment]
Try the latest https://github.com/InfinityGamers/HungerGames-UPDATED/releases/latest and make sure your game level is set correctly, use ```/hg level <game> <level>``` or in your arena config.
