### ISSUE TITLE
Map Reset Doesn't work, no matter what

### ISSUE THREAD

**Issue by Vladucul** [InfinityGamers/HungerGames#75]
The Console does say, after finishing a skywars game, [Hunger Games] Resetting Map for SW-1, but if I play on the same game, the map remains unresetted, and blocks that have been modified in the previous round remain there.

**Comment by Vladucul** [comment]
I am using the latest version, for API 3.0.0-ALPHA10, on a server running API 3.0.0-ALPHA11. That might be the issue?

**Comment by CarlosCraft1145** [comment]
If that was the issue, then the plugin usually won't load

**Comment by xBeastMode** [comment]
Check the new commit.
