### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kaitododoyt** [InfinityGamers/HungerGames#9]
First, thanks for the plugin

2nd: this is the bug that occurs in game https://www.youtube.com/watch?v=630gb-msqm0

3rd: Now, error in players quit: 
[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'HungerGames vbuild#07': Access to undeclared static property: xbeastmode\hg\HGManagement::$BBlocks on xbeastmode\hg\Events
[16:30:12] [Server thread/CRITICAL]: Error: "Access to undeclared static property: xbeastmode\hg\HGManagement::$BBlocks" (EXCEPTION) in "/HG.phar/src/xbeastmode/hg/api/EndGame" at line 76

**Comment by xBeastMode** [comment]
If you are using a third party build of PocketMine the moving bug will not be fixed. This plugin only works properly with the official PocketMine-MP. Download latest release to fix the quit eror.
